# Generated by Django 3.1 on 2020-09-18 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20200918_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='is_watched',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 18, 13, 46, 58, 863691)),
        ),
        migrations.AlterField(
            model_name='bid',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 18, 13, 46, 58, 863691)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 18, 13, 46, 58, 864689)),
        ),
    ]
