# Generated by Django 3.1 on 2020-09-18 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_auto_20200918_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='is_watched',
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 18, 14, 35, 13, 886047)),
        ),
        migrations.AlterField(
            model_name='bid',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 18, 14, 35, 13, 887080)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 18, 14, 35, 13, 887080)),
        ),
    ]
