# Generated by Django 3.1 on 2020-09-18 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_auto_20200918_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='highest_bid',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 0, 58, 1, 828033)),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='starting_bid',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bid',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 0, 58, 1, 828033)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 0, 58, 1, 829031)),
        ),
    ]
